alias: Dehumidifier Control
# Controls dehumidifier based on outside temperature and optimizes humidity setpoint
description: >
  Turn off dehumidifier above 10°C. When 2..10°C, ensure it is on and set
  humidity to a value (25..60%) linearly interpolated from outside temperature.
triggers:
  # Trigger: outside temperature changes (via weather entity)
  - entity_id: weather.forecast_home
    trigger: state
conditions:
  # Only act if temperature changes by at least 1°C (prevents frequent triggers)
  - condition: template
    value_template: >-
      {% set old = trigger.from_state.attributes.temperature | float(0) %} {%
      set new = trigger.to_state.attributes.temperature | float(0) %} {{ (old -
      new) | abs >= 1 }}
actions:
  - choose:
      # If outside temperature > 10°C, turn off humidifier
      - alias: Turn off humidifier when outside temperature > 10°C
        conditions:
          - condition: template
            value_template: >-
              {{ state_attr('weather.forecast_home','temperature') | float(999)
              > 10.0 }}
        sequence:
          # Capture child lock state for this branch
          - alias: Capture child lock state
            variables:
              was_locked: >-
                {{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}
          # If child lock is enabled, disable it first
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_off
                    data: {}
                  - wait_for_trigger:
                      - entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                        to: "off"
                        trigger: state
                    timeout: "00:00:05"
                  - delay: "00:00:01"
            default: []
          # Power off humidifier
          - alias: Power off humidifier
            target:
              entity_id: humidifier.otto_dehumidifier_eeese_air_care
            action: humidifier.turn_off
            data: {}
          # If child lock was enabled, re-enable it
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ was_locked | bool }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_on
                    data: {}
            default: []
      # If inside humidity > 60% and outside temp > t_max, turn on humidifier and set to 60%
      - alias: Turn on humidifier and set to 60% if inside humidity > 60% and outside temp > 10°C
        conditions:
          - condition: template
            value_template: >-
              {{ state_attr('humidifier.otto_dehumidifier_eeese_air_care', 'humidity') | float(0) > 60 }}
          - condition: template
            value_template: >-
              {{ state_attr('weather.forecast_home','temperature') | float(0) > 10.0 }}
        sequence:
          # Capture child lock state for this branch
          - alias: Capture child lock state
            variables:
              was_locked: >-
                {{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}
          # If child lock is enabled, disable it first
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_off
                    data: {}
                  - wait_for_trigger:
                      - entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                        to: "off"
                        trigger: state
                    timeout: "00:00:05"
                  - delay: "00:00:01"
            default: []
          # Power on humidifier
          - alias: Power on humidifier
            target:
              entity_id: humidifier.otto_dehumidifier_eeese_air_care
            action: humidifier.turn_on
            data: {}
          # Set humidifier target humidity to 60%
          - alias: Set humidifier target humidity to 60%
            target:
              entity_id: humidifier.otto_dehumidifier_eeese_air_care
            data:
              humidity: 60
            action: humidifier.set_humidity
          # Update stored setpoint input_number to 60
          - alias: Update stored setpoint input_number to 60
            target:
              entity_id: input_number.dehumidifier_setpoint
            data:
              value: 60
            action: input_number.set_value
          # If child lock was enabled, re-enable it
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ was_locked | bool }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_on
                    data: {}
            default: []
      # If outside temperature ≤ 10°C, ensure humidifier is on
      - alias: Turn on humidifier when outside temperature ≤ 10°C
        conditions:
          - condition: template
            value_template: >-
              {{ state_attr('weather.forecast_home','temperature') | float(999) <= 10.0 }}
          - condition: state
            entity_id: humidifier.otto_dehumidifier_eeese_air_care
            state: 'off'
        sequence:
          # Capture child lock state for this branch
          - alias: Capture child lock state
            variables:
              was_locked: >-
                {{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}
          # If child lock is enabled, disable it first
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_off
                    data: {}
                  - wait_for_trigger:
                      - entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                        to: "off"
                        trigger: state
                    timeout: "00:00:05"
                  - delay: "00:00:01"
            default: []
          # Power on humidifier
          - alias: Power on humidifier
            target:
              entity_id: humidifier.otto_dehumidifier_eeese_air_care
            action: humidifier.turn_on
            data: {}
          # If child lock was enabled, re-enable it
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ was_locked | bool }}"
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_on
                    data: {}
            default: []
      # If outside temperature is 2–10°C, ensure humidifier is on and set humidity
      - alias: >-
          Ensure humidifier is on and set humidity when outside temperature is
          between 2°C and 10°C
        conditions:
          # Only run if temperature is ≤ 10°C
          - condition: template
            value_template: >-
              {{ state_attr('weather.forecast_home','temperature') | float(999) <= 10.0 }}
          # Only proceed if setpoint differs from outside temp by >= 1°C
          - condition: template
            value_template: |-
              {{ (states('input_number.dehumidifier_setpoint') | float(0) -
                  ( state_attr('weather.forecast_home','temperature') | float(0) ) ) | abs >= 1 }}
            alias: >-
              Only proceed when the stored setpoint differs from outside
              temperature by >= 1°C (prevents frequent small adjustments)
        sequence:
          # Compute desired humidity and capture child-lock state
          - alias: Compute desired humidity and capture child-lock state
            variables:
              t: >-
                {{ state_attr('weather.forecast_home','temperature') | float(0) }}
              t_min: 2
              t_max: 10
              h_min: 25
              h_max: 60
              desired_humidity: |-
                {% if t <= t_min %}
                  {{ h_min | round(0) }}
                {% elif t >= t_max %}
                  {{ h_max | round(0) }}
                {% else %}
                  {% set slope = (h_max - h_min) / (t_max - t_min) %}
                  {{ (h_min + slope * (t - t_min)) | round(0) }}
                {% endif %}
          # Capture child lock state for this branch
          - alias: Capture child lock state
            variables:
              was_locked: >-
                {{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}
          # Ensure humidifier is powered on if off, handling child lock
          - choose:
              - conditions:
                  - condition: state
                    entity_id: humidifier.otto_dehumidifier_eeese_air_care
                    state: 'off'
                sequence:
                  # If child lock is enabled, disable it first
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ is_state('switch.otto_dehumidifier_eeese_air_care_child_lock','on') }}"
                        sequence:
                          - target:
                              entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                            action: switch.turn_off
                            data: {}
                          - wait_for_trigger:
                              - entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                                to: "off"
                                trigger: state
                            timeout: "00:00:05"
                          - delay: "00:00:01"
                    default: []
                  # Power on humidifier
                  - target:
                      entity_id: humidifier.otto_dehumidifier_eeese_air_care
                    action: humidifier.turn_on
                    data: {}
                  # If child lock was enabled, re-enable it
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ was_locked | bool }}"
                        sequence:
                          - target:
                              entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                            action: switch.turn_on
                            data: {}
                    default: []
          # Wait for humidifier to report state 'on'
          - alias: Wait for humidifier to report state 'on'
            wait_for_trigger:
              - entity_id: humidifier.otto_dehumidifier_eeese_air_care
                to: "on"
                trigger: state
            timeout: "00:00:10"
          # If child lock was enabled, temporarily disable it
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ was_locked | bool }}"
                alias: >-
                  Temporarily disable child lock so the device will accept
                  configuration commands
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_off
                    data: {}
                  - wait_for_trigger:
                      - entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                        to: "off"
                        trigger: state
                    timeout: "00:00:05"
                  - delay: "00:00:01"
            default: []
          # Set humidifier target humidity (min 25%)
          - alias: Set humidifier target humidity
            target:
              entity_id: humidifier.otto_dehumidifier_eeese_air_care
            data:
              humidity: "{{ desired_humidity | int }}"
            action: humidifier.set_humidity
          # Update stored setpoint input_number (min 25%)
          - alias: Update stored setpoint input_number
            target:
              entity_id: input_number.dehumidifier_setpoint
            data:
              value: "{{ desired_humidity | int }}"
            action: input_number.set_value
          # If child lock was enabled, re-enable it
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ was_locked | bool }}"
                alias: Re-enable child lock if it was previously enabled
                sequence:
                  - target:
                      entity_id: switch.otto_dehumidifier_eeese_air_care_child_lock
                    action: switch.turn_on
                    data: {}
            default: []
